### ISSUE TITLE
Error message when i try to go into library

### ISSUE THREAD

**Issue by Theokind** [SrJuggernaut/character-tools#13]
![image](https://github.com/SrJuggernaut/character-tools/assets/139943937/6e8a3cf7-ab98-4e8c-b8ea-87e4edf7657e)

I've started getting this error message today. It started out by not letting me save edits, then it just started displaying this whenever i clicked on my library. I still can't go into the library or save cards, started ~5 hours ago. Does anyone know whats wrong?

**Comment by SrJuggernaut** [comment]
It seems like a database error, I guess this happens to you in every window you open? Could you please tell me what browser you are using and the version to see if I can find out something?

**Comment by Theokind** [comment]
I fixed it and forgot to mention, updating my browser caused it to be fine. There is another issue though, when I try to import a character library I get this error.
![image](https://github.com/SrJuggernaut/character-tools/assets/139943937/44161263-d4de-47c4-a028-45ff4cd723e8)

I haven't changed the library in anyway since I exported it, and I'm not sure whats wrong.
