### ISSUE TITLE
Error while exporting character PNG V2

### ISSUE THREAD

**Issue by Pablo4096** [SrJuggernaut/character-tools#15]
I have been using the editor for a long time, but after the last update I can't export the card because I get an error PNG V2. Maybe I am just doing something wrong?
The error appears even when I load the card PNG V2 and without modification I want to export it.

"Error while exporting character
property "image" is non-configurable and can't be deleted"

**Comment by SrJuggernaut** [comment]
Yes, I can reproduce the bug, I probably introduced it in yesterday's update, I will try to fix it today, thank you very much for reporting.

**Comment by SrJuggernaut** [comment]
I've already uploaded a fix, and the bug seems to be unreproducible, once again thanks for reporting the bug

**Comment by Pablo4096** [comment]
Thank you for fixing the editor.
