### ISSUE TITLE
V2 card loading problem

### ISSUE THREAD

**Issue by Pablo4096** [SrJuggernaut/character-tools#17]
Hi again.
I have a problem loading some V2 cards downloaded from chub.ai . I have attached an example card.

"Error while importing character
The character could not be imported"

![main_Lola_spec_v2](https://github.com/user-attachments/assets/f39d95bd-b9b3-457c-a913-84f86b72466a)

**Comment by SrJuggernaut** [comment]
This is actually not a problem with the tool, but with the card itself, according to [the specification](https://github.com/malfoyslastname/character-card-spec-v2/blob/main/spec_v2.md#alternate_greetings) the `alternate_greetings` field should be an array of strings, but the card has a string instead.
```json
{
  "data": {
    "alternate_greetings": "1687194031049",
    //... 
  },
  "spec": "chara_card_v2",
  "spec_version": "2.0"
}
```
