### ISSUE TITLE
Exporting CharacterBook don't work

### ISSUE THREAD

**Issue by glimmeflokk** [SrJuggernaut/character-tools#20]
Thanks for an excellent tool. However, one feature doesn't seem to work: Exporting CharacterBook.

When I go to the CharacterBook editor [link](https://character-tools.srjuggernaut.dev/characterbook-editor), if I create a new CharacterBook and go to the "Export or Save" fan, it will export the CharacterBook upon pressing the JSON button on the right (below Export Character Book). However, if I save the CharacterBook first, nothing happens when I press the JSON button. Same if I import a CharacterBook embedded in a character - if the CharacterBook is saved and present in the CharacterBook Library page, it will not export (nothing happens when pressing the JSON button mentioned before).

Tested on Windows and MacOS across browsers and computers. Even tested on browsers with no plugins, so I don't think it's caused by my setup.

**Comment by SrJuggernaut** [comment]
Thank you very much for reporting the bug, it is a bug created by type problems, I must have introduced it in one of the last commits, could you check this preview where it should be fixed? https://fix-id-not-configurable.character-tools.pages.dev

**Comment by glimmeflokk** [comment]
> Thank you very much for reporting the bug, it is a bug created by type problems, I must have introduced it in one of the last commits, could you check this preview where it should be fixed? https://fix-id-not-configurable.character-tools.pages.dev

Thank you for checking up on this so quickly. It is indeed fixed (working) on the link you provided. Thanks once again!

**Comment by SrJuggernaut** [comment]
Ok the changes are now in the main site, thanks again for reporting and use the tool <3
